Vagrant.configure("2") do |config|

    config.vm.define :precise do |precise|
        precise.vm.provider :virtualbox do |v|
            v.name = "phansible-roles-precise-test"
            v.customize ["modifyvm", :id, "--memory", 512]
        end

        precise.vm.network :private_network, ip: "192.168.13.121"

        precise.vm.box = "precise64"
        precise.vm.box_url = "http://files.vagrantup.com/precise64.box"
    end

    config.vm.define :trusty do |trusty|
        trusty.vm.provider :virtualbox do |v|
            v.name = "phansible-roles-trusty-test"
            v.customize ["modifyvm", :id, "--memory", 512]
        end

        trusty.vm.network :private_network, ip: "192.168.13.122"

        trusty.vm.box = "trusty64"
        trusty.vm.box_url = "https://vagrantcloud.com/ubuntu/trusty64/version/1/provider/virtualbox.box"
    end

    config.vm.define :lucid do |lucid|
        lucid.vm.provider :virtualbox do |v|
            v.name = "phansible-roles-lucid-test"
            v.customize ["modifyvm", :id, "--memory", 512]
        end

        lucid.vm.network :private_network, ip: "192.168.13.123"

        lucid.vm.box = "lucid64"
        lucid.vm.box_url = "http://files.vagrantup.com/lucid64.box"

    end

    config.ssh.forward_agent = true

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "test_playbook.yml"
    end

    config.vm.synced_folder "./test_app", "/vagrant", id: "vagrant-root", :nfs => true
end
