tools:
  php_code_sniffer:
    enabled: true
    config:
        standard: "PSR12"
  php_cpd: true
  php_mess_detector: true
  php_loc: true
  php_cs_fixer: true

checks:
  php:
    code_rating: true
    duplication: true
    unused_variables: true
    unused_properties: true
    unused_methods: true

build:
  environment:
    php:
      version: 8.3.11
  dependencies:
    override:
      - 'composer install --no-interaction --prefer-dist'
  tests:
    override:
      - 'bin/phpunit --configuration phpunit.xml.dist'

filter:
  paths:
    - src
    - tests
  excluded_paths:
    - 'app/*'
    - 'ansible/*'
    - 'src/Phansible/Resources/ansible/*'
