tools:
  php_code_sniffer:
    enabled: true
    config:
        standard: "PSR12"
  php_cpd: true
  php_mess_detector: true
  php_loc: true
  php_cs_fixer: true

build:
  environment:
    php:
      version: 8.3.11
  dependencies:
    override:
      - 'composer install --no-interaction --prefer-dist'
  tests:
    override:
      - 'vendor/bin/phpunit --configuration phpunit.xml.dist'
filter:
  paths:
    - src
    - tests
  excluded_paths:
    - 'app/*'
    - 'ansible/*'
    - 'src/Phansible/Resources/ansible/*'

hecks:
    php:
        code_style:
            php5_style_constructor: false
            remove_php4_constructors: true
        code_size:
            max_class_size: 500
            max_method_size: 50
        code_rating: true
        duplication: true
        security: true
        unused_variables: true
        unused_properties: true
        unused_methods: true

coding_style:
    php:
        spaces:
            indent_style: space
            indent_size: 4
        braces:
            inline: false
            new_line_for_else: true
        operators:
            align_equals: true

repository:
    branches:
        pull_requests: true
        all: true  # This makes it run on all branches, not just PRs

