tools:
  php_code_sniffer:
    enabled: true
    config:
        standard: "PSR12"
  php_cpd: true
  php_mess_detector: true
  php_loc: true
  php_cs_fixer:
    enabled: true
    config:
      level: "PSR12"
      fixers: ["@PSR12"]

checks:
  php:
    code_rating: true
    duplication: true
    unused_variables: true
    unused_properties: true
    unused_methods: true

build:
  before_commands:
    - rm -rf /home/scrutinizer/.analysis/phpcs/vendor/*
    - composer require squizlabs/php_codesniffer:^3.7 --dev
  environment:
    php:
      version: 8.3.11
  dependencies:
    override:
      - 'composer install --no-interaction --prefer-dist'
  tests:
    override:
      - 'bin/phpunit --configuration phpunit.xml.dist'

filter:
  paths:
    - src
    - tests
  excluded_paths:
    - 'app/*'
    - 'ansible/*'
    - 'src/Phansible/Resources/ansible/*'
