tools:
  php_code_sniffer:
    enabled: true
    config:
        standard: "PSR12"
  php_cpd: true
  php_mess_detector: true
  php_loc: true
  php_cs_fixer: true

build:
  environment:
    php:
      version: 8.3.11
  dependencies:
    override:
      - 'composer install --no-interaction --prefer-dist'
  tests:
    override:
      - 'vendor/bin/phpunit --configuration phpunit.xml.dist'
filter:
  paths:
    - src
    - tests
  excluded_paths:
    - 'app/*'
    - 'ansible/*'
    - 'src/Phansible/Resources/ansible/*'

checks:
  php:
    code_rating: true
    duplication: true
    coding_standard: PSR12  # Specify a coding standard if preferred
    unused_variables: true
    unused_properties: true
    unused_methods: true

repository:
    branches:
        pull_requests: true
        all: true  # This makes it run on all branches, not just PRs
