checks:
  php:
    code_rating: true
    duplication: true
    unused_variables: true
    unused_properties: true
    unused_methods: true

build:
  nodes:
    analysis:
      tests:
        override:
        - phpcs-run

  environment:
    php:
      version: 8.3.11
  dependencies:
    override:
      - 'composer install --no-interaction --prefer-dist'
  tests:
    override:
      - 'XDEBUG_MODE=coverage bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.clover'
      - 'wget https://scrutinizer-ci.com/ocular.phar'
      - 'php ocular.phar code-coverage:upload --format=php-clover coverage.clover'

filter:
  paths:
    - src
    - tests
  excluded_paths:
    - 'app/*'
    - 'ansible/*'
    - 'src/Phansible/Resources/ansible/*'
